import createClient from "openapi-fetch";
import type { paths } from "./generated/schema"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "https://localhost:7059" });

export default client;