import type { paths, components } from "./generated/schema"; // generated by openapi-typescript

// Schema Obj
type MyModel = components["schemas"]["MyModel"];
type ProbmlemDetails = components["schemas"]["ProblemDetails"];

// Path params
type EndpointParams = paths["/v1/api/my-endpoint"]["parameters"];

// Response obj
type SuccessResponse =
  paths["/v1/api/my-endpoint"]["get"]["responses"][200]["content"]["application/json"];
type ErrorResponse =
    paths["/v1/api/my-endpoint"]["get"]["responses"][400]["content"]["application/json"];